### ISSUE TITLE
Fully rendered embedded notes

### ISSUE THREAD

**Issue by ChildishhAlbino** [HiDeoo/starlight-obsidian#13]
### Is your feature request related to a problem?

The embedded note renders on my website differently than the content I see in obsidian.

### Describe the solution you'd like

I'd like the rendered webpage to have fully highlighted links and not contain frontmatter fields or text. 

### Describe alternatives you've considered

For now I see no alternative to this as embedding notes is inconsistent between the vault view in Obsidian and the rendered Astro page are too different for this feature to be used in a heavily linked vault.

## Obsidian
![image](https://github.com/HiDeoo/starlight-obsidian/assets/36402974/6e806648-8a73-4cfd-915d-ed61d583371d)

## Astro
![image](https://github.com/HiDeoo/starlight-obsidian/assets/36402974/008a5c6d-aaff-4423-b0d4-487783966cae)

**Comment by ChildishhAlbino** [comment]
I do understand this might a low ROI on time investment for people who might use it but wanted to raise this a feature request so it can be tracked in case myself or anyone else has time to give it in future. 

I think it could be achieved simply rendering the markdown content of the page into HTML and then embedding it into the page within an indent but I am not sure how well that would scale with large vaults etc.

**Comment by ChildishhAlbino** [comment]
hey @HiDeoo

I decided to take a look at the repo and try to find the bug - I think it's coming from this function (I tried creating a branch but I don't have permissions which is fine). I'd really like to get this feature working to improve how I track my DND campaign's timeline and reduce duplication of the same notes.

![image](https://github.com/HiDeoo/starlight-obsidian/assets/36402974/7e368ca9-fea9-4c8c-8cd8-17049437771a)

I've pieced this understanding together and I can't get Remark to like using async functions so let me know if there's something I've missed or that you know is causing the issue.

**Comment by HiDeoo** [comment]
Thanks for your report and patience :raised_hands:

Your very thorough investigation helped a lot as you pinpointed the issue perfectly. We cannot really use the string version in this spot but knowing the issue, a refactor to avoid `processor.parse` (which does not run transformers) was possible.

The test fixture we had for this case was very basic and not sufficient to catch this issue (and I am personally pretty much never using embedded notes). I've added a new one which before the changes reproduces your issue:

<img width="745" alt="SCR-20240430-lvcj" src="https://github.com/HiDeoo/starlight-obsidian/assets/494699/a0493645-8d65-469d-80e1-6d17a990c977">

After the changes, the same page now renders correctly (ignore the PDF rendering issue which is another issue with the Chrome DevTools when capturing a full page size screenshot):

![after](https://github.com/HiDeoo/starlight-obsidian/assets/494699/217c879b-c85e-4500-89c8-c91a85642970)

The changes are now available in version [`0.4.3`](https://github.com/HiDeoo/starlight-obsidian/releases/tag/v0.4.3) that I just released :tada:

Thanks a lot!

**Comment by ChildishhAlbino** [comment]
Thank you @HiDeoo - that is awesome work. Glad to be of help improving this awesome plugin.

I've noticed one small issue with embedded notes that use frontmatter. I've raised https://github.com/HiDeoo/starlight-obsidian/issues/17 to address it.
