### ISSUE TITLE
Embedded notes render their frontmatter as plaintext

### ISSUE THREAD

**Issue by ChildishhAlbino** [HiDeoo/starlight-obsidian#17]
### Describe the bug

![image](https://github.com/HiDeoo/starlight-obsidian/assets/36402974/95b942c2-e187-440b-a05e-3218d5dcbc84)

The title should hopefully be descriptive alongside this image. I don't know if this something that can be turned off easily but it's quite frustrating as there's a lot of frontmatter used in my obsidian vaults.

### To Reproduce

1. Clone this repo and install dependencies of the example site to run locally.
2. Create a page with frontmatter properties `foo` and `bar` with whatever values you want as well as placeholder content.
3. Embed that page within another page and run the local server.
4. Review the rendered results.

### Expected behavior

The frontmatter content should not be rendered when the page is embedded.

### How often does this bug happen?

Every time

### System Info

Windows 11
Chrome 124.0.6367.119

**Comment by HiDeoo** [comment]
Thanks for the report, this should now be fixed in [`v0.4.5`](https://github.com/HiDeoo/starlight-obsidian/releases/tag/v0.4.5) :tada:
