### ISSUE TITLE
Symlink files to vault rather than copying them

### ISSUE THREAD

**Issue by ChildishhAlbino** [HiDeoo/starlight-obsidian#23]
### Is your feature request related to a problem?

I update some content from a vault within a code editor/whist developing features for the site and I have to reload the developer environment to see those changes.

### Describe the solution you'd like

Either some mechanism for detected changed files within the vault path that copies the new version into the `src/content/docs` folder OR the ability to opt into using symbolically links files/folders instead of a raw copy.

That way the development server can stay loaded the entire time and content will refresh as if it was always in the content directory.

### Describe alternatives you've considered

I considered trying to build something like this myself first but thought I should ask first.

**Comment by HiDeoo** [comment]
Thanks for the feedback.

Symlinking is not an option in this case as files from the vault are not just copied. They are actually processed, edited and then the result of this processing will be saved.

This kind of workflow is not one I envision for the plugin which is closer to the one from Obsidian Publish where you edit the vault, and then manually publish it at some point in time. Watching the vault for changes and automatically handling them properly would require quite a bit of work and add some complexity to the plugin that I'm not sure is worth it.

As a workaround, a potential solution could be for a usere to manually add a custom Astro integration that would use the [`addWatchFile`](https://docs.astro.build/en/reference/integrations-reference/#addwatchfile-option) helper:

```js
// astro.config.mjs
export default defineConfig({
  integrations: [
    starlight({ … }),
    {
      name: 'watch-vault',
      astro:config:setup': ({ addWatchFile }) => {
        addWatchFile('path/to/vault/file');
      },
    },
  ],
});
```

I'll keep an eye out to see if I get some more feedback on this and if it's a common request, I might reconsider adding this feature.

**Comment by ChildishhAlbino** [comment]
Just a couple updates;

1. due to the location of my vault(s) within my project it seems they're already being watched by Astro and it does seem to restart the server 
2. however, despite the server restarting - Astro does not seem to reload the config each time content changes so it doesn't result in this plugin's transformations taking place again.

A bit of a bummer but it is what it is - thanks for trying to help :D I understand your reasoning for avoiding this even for just development mode.
