### ISSUE TITLE
Pages with date as title (diary entries) cannot be processed. frontmatter does not match collection schema.

### ISSUE THREAD

**Issue by caspargross** [HiDeoo/starlight-obsidian#24]
### Describe the bug

Hi, thanks for creating the plugin.

I have a standard obsidian layout with a `11_diary/` folder containing notes where the filename is the date on which they were created. 
When building it get the following error:
```
20:12:31 [ERROR] [vite] x Build failed in 8.18s
[InvalidContentEntryFrontmatterError] [astro:content-imports] docs → wiki/11_diary/2018-11-21.md frontmatter does not match collection schema.
title: Expected type `"string"`, received "date"
file: /home/caspar/dev/wiki_web/src/content/docs/wiki/11_diary/2018-11-21.md?astroContentCollectionEntry=true:0:0
  Hint:
    See https://docs.astro.build/en/guides/content-collections/ for more information on content schemas.
  Error reference:
    https://docs.astro.build/en/reference/errors/invalid-content-entry-frontmatter-error/
  Stack trace:
    at getEntryData (file:///home/caspar/dev/wiki_web/node_modules/astro/dist/content/utils.js:74:26)
    at async Object.transform (file:///home/caspar/dev/wiki_web/node_modules/astro/dist/content/vite-plugin-content-imports.js:89:67)
    at async ModuleLoader.addModuleSource (file:///home/caspar/dev/wiki_web/node_modules/rollup/dist/es/shared/node-entry.js:19003:36)
```

It looks like astro / vite parses the title as date instead of string. 

### To Reproduce

create a note with a filname that resembles a date (`2024-08-18.md`) and build it with starlight-obsidian. 

### Expected behavior

Page title should always be a string. 

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for your feedback :raised_hands:

This should be fixed in the latest version [`0.4.7`](https://github.com/HiDeoo/starlight-obsidian/releases/tag/v0.4.7) that I just released.
