### ISSUE TITLE
Transformed files with lastUpdated in Frontmatter cause errors with Starlight typechecking

### ISSUE THREAD

**Issue by ChildishhAlbino** [HiDeoo/starlight-obsidian#28]
### Describe the bug

From the following frontmatter:
<img width="301" alt="Input frontmatter" src="https://github.com/user-attachments/assets/ba588d7b-23ac-4142-aff5-d2b175fcae8b">

The output file is produced:
<img width="293" alt="output frontmatter" src="https://github.com/user-attachments/assets/5d14bf29-834f-4cdc-b1d0-2d500b719d82">

Causing this error with Starlight:
<img width="1223" alt="starlight error" src="https://github.com/user-attachments/assets/61c6190d-90ff-4fe5-b503-c97bce245644">

I tested removing the `"` from the output file and that fixed this issue.

### To Reproduce

1. Create a project with this plugin (`copyStarlightFrontmatter: true`) and a simple Obsidian Vault and a singular empty note. 
1. Populate the a frontmatter containing `lastUpdated: 2024-09-21` (I've tested other dates cause the same error)
1. Run the dev server and observe the outcome

### Expected behavior

The page should load and the date set in the frontmatter should be shown at the bottom of the page

### How often does this bug happen?

Every time

### System Info

- MacOS 14.6 (23G80)
- Chrome

### Additional Context

This used to work - only noticed the issue earlier today, not sure what or when it was introduced

**Comment by HiDeoo** [comment]
Thanks for the report :raised_hands: 

I assume this regression was introduced in the [`0.4.7`](https://github.com/HiDeoo/starlight-obsidian/releases/tag/v0.4.7) version but should now be fixed in the [`0.4.9`](https://github.com/HiDeoo/starlight-obsidian/releases/tag/v0.4.9) version that I just released.

**Comment by ChildishhAlbino** [comment]
Thanks for the swift fix! You're a weapon!
