### ISSUE TITLE
Option to allow copying arbitrary frontmatter properties

### ISSUE THREAD

**Issue by caro401** [HiDeoo/starlight-obsidian#30]
### Is your feature request related to a problem?

Currently the only frontmatter keys that can be copied into my starlight content collection are those hard-coded in [`starlightFrontmatterKeys`](https://github.com/HiDeoo/starlight-obsidian/blob/main/packages/starlight-obsidian/libs/starlight.ts#L51). However, Starlight allows you to [extend their default frontmatter](https://starlight.astro.build/reference/frontmatter/#customize-frontmatter-schema) to add your own keys. I'd like to make use of some frontmatter I have in my vault via some overridden starlight components.

### Describe the solution you'd like

Could you consider allowing the current `copyStarlightFrontmatter` to copy all frontmatter keys by default, with the understanding that if the content collection config for Starlight doesn't contain a given key, it will be dropped (as Zod discards any keys it doesn't know about). I believe this wouldn't change the existing behaviour of that option for most users.

### Describe alternatives you've considered

Alternatively, could there be an additional configuration option to allow copying all frontmatter keys, not just the ones Starlight knows about by default. I don't have opinions whether this is a separate key in the configuration, or a different value other than true/false for `copyStarlightFrontmatter`.

Alternatively again, you could perhaps work out what the frontmatter keys starlight knows about are from the starlight content collection configuration you're working with, rather than hard-coding only the default values? I'm not sure whether that's a possibility for starlight integrations. But this seems to be just duplictaing the work of dropping unknown keys that Zod is already doing.

### Additional Context

Happy to contribute code.

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands: 

I think this totally makes sense, not something I had considered before. I'm leaning towards the idea of deprecating `copyStarlightFrontmatter` with proper error explanation on how to update and introduces a new `copyFrontmatter` option which could accept either `none` (which would still be the default like now), `starlight` (which would be the equivalent of the current `true` option) or `all` (which would copy all frontmatter as you suggested).

I'll take the night to think about it and see if I'm happy with the idea and if so, I'll implement it tomorrow. Thanks for the suggestion!

**Comment by HiDeoo** [comment]
Thanks again for the feedback :raised_hands:

I just published [version `0.5.0`](https://github.com/HiDeoo/starlight-obsidian/releases/tag/v0.5.0) that includes the new [`copyFrontmatter`](https://starlight-obsidian.vercel.app/configuration/#copyfrontmatter) option.
