### ISSUE TITLE
Respect Starlight frontmatter properties already present in source files

### ISSUE THREAD

**Issue by ChildishhAlbino** [HiDeoo/starlight-obsidian#6]
### Describe the bug

If a source file has frontmatter properties that would be used by starlight; it would be very useful to respect those in the generated output file.

I.e.
The source file
![image](https://github.com/HiDeoo/starlight-obsidian/assets/36402974/b77cc224-7339-41cb-9341-fe8c7f92df55)

The generated file
![image](https://github.com/HiDeoo/starlight-obsidian/assets/36402974/317d64e5-4d81-4ab1-bf02-7d2b5a86faea)

### To Reproduce

1. Create a file in an obsidian vault with the title frontmatter property and assign a value different than the title of the page in obsidian
2. Run `npm run dev` and observe the associated output file.
3. Compare the frontmatter properties.

### Expected behavior

The assigned frontmatter; where possible, should be respected.

### How often does this bug happen?

Every time

### System Info

Windows 11 (WSL Ubuntu)
Node 18.19.1

**Comment by HiDeoo** [comment]
Thanks for the feedback, super appreciated :raised_hands:

This is a bit of a tricky subject. A user may use a Starlight known frontmatter fields with a different value type or format. An Obsidian plugin could also do the same. Automatically copying known Starlight frontmatter fields by default would require validating all the fields individually, and only copying the ones that are valid and match Starlight expectations. But even then, a user may use a frontmatter field in Obsidian with a value that matches the Starlight expectations but still want that field to be only used in Obsidian and not copied to the Starlight file.

Considering all this, I just released the version [`0.4.0`](https://github.com/HiDeoo/starlight-obsidian/releases/tag/v0.4.0) of the plugin with a new [`copyStarlightFrontmatter`](https://starlight-obsidian.vercel.app/configuration/#copystarlightfrontmatter) option, defaulting to `false`. When set to `true`, the plugin will copy all known Starlight frontmatter fields from an Obsidian file to the associated generated page. As the known fields are copied as is, it's up to the user to manually enable this option and ensure that the frontmatter fields in their Obsidian files match the Starlight expectations.

**Comment by ChildishhAlbino** [comment]
Awesome - I shall try that out. Appreciate it :D
