### ISSUE TITLE
Error when Generating Starlight pages from Obsidian vault on Windows 11

### ISSUE THREAD

**Issue by Symplectos** [HiDeoo/starlight-obsidian#9]
### Describe the bug

Good morning.

When trying to use starlight-obsidian on Windows 11 (sorry, my laptop is broken), the generation of the pages fails because a directory containing the absolute path of the given Obsidian vault is attempted to be created.

**Error Message**
```
08:40:15 [starlight-obsidian-plugin] Generating Starlight pages from Obsidian vault…
08:40:15 [ERROR] [starlight-obsidian-plugin] O:/Obsidian Vaults/Starlight Test/Welcome.md — ENOENT: no such file or directory, mkdir 'O:\Astro Starlight\DTL\Virstand\starlight\src\content\docs\notes\O:\Obsidian Vaults\Starlight Test'
08:40:15 [ERROR] [starlight-obsidian-plugin] Failed to generate some Starlight pages. See the error(s) above for more information.
[AstroUserError] Failed to generate Starlight pages from Obsidian vault.
```

This happens independently of the locations or names for the Obsidian vault, or whether the vault location is specified with relative or absolute path in the Starlight config, i.e. both configs below lead to the same type of error:

```
vault: 'O:/Obsidian Vaults/Starlight Test'
vault: '../vault
```

Thank you. Kind regards,
Gilles

P.S.: Thank you for the great project, and the idea with the Obsidian plugin.

### To Reproduce

Fresh Installation of NodeJS (LTS) on Windows 11. Jetbrains Webstorm terminal.

1. npm create astro@latest -- --template starlight
2. cd .\starlight
3. npm install starlight-obsidian
4. configure astro.config.mjs to set the path to a newly created Obsidian vault
5. npm run dev

### Expected behavior

The expected behaviour would be to perhaps create the pages in a sub-folder containing only the name of the Obsidian vault, not the entire path.

### How often does this bug happen?

Every time

### System Info

- Operating System: Windows 11
- IDE: Jetbrains Webstorm 2023.3.5
- Astro Starlight: v0.21.1
- Astro Starlight Obsidian Plugin: v0.4.0
- NPM Version: 10.5.0
- NodeJS: 20.11.1

**Comment by HiDeoo** [comment]
Thanks for your report 🙌 

I just published [`v0.4.1`](https://github.com/HiDeoo/starlight-obsidian/releases/tag/v0.4.1) which should fix the issues you encountered. 

I only had a temporary access to a Windows 10 machine but my guess would be that the errors are not version-specific but mostly just handling Windows paths and line endings correctly.
